---
title: "Template Letter to the Mayor Regarding the Conditions of New Yorkers during COVID-19"
---

*Dear Mayor Adams*,

I am writing this letter to express the concerns that arose in New York City during the early stages of the Global COVID-19 pandemic and how important a role GIS can play in emergency response. Although 5 years after the outbreak, It remains important to fully understand and process past events in order to develop a plan for addressing similar crises in the future.


The COVID-19 pandemic in its early stages hit the world hard. As the virus spread rapidly, cities like New York, Milan, and Wuhan became epicenters of the crisis, experiencing an exponential rise in cases that strained resources and left governments scrambling to respond. These hotspots saw hospitals overwhelmed with patients, critical shortages of medical supplies, and the urgent need for coordinated responses at local, national, and international levels. The speed with which the virus spread exposed vulnerabilities in public health infrastructure, while also highlighting the importance of timely, data-driven decision-making to mitigate its effects.

```{ojs}
//| echo: false
Plot.plot({
  width:5000,
  height: 120,
  marks: [
    Plot.text([" The US in particular, in April of 2020, became the top global hotspot having more than 500,000 confirmed cases by that point (CDC)."], {frameAnchor: "middle", fill: 'red', fontSize: 120 })
  ]
})
```

The above visual only shows COVID-19 in New York State, not in just NYC which was considered the global hotspot at one point. In order to better manage a crisis as such, GIS could have been implemented more to visualize the spread of the virus. More specifically, it's crucial to look at the number of positive cases by MODZCTA (something similar to zipcodes). The below ArcGIS dashboard effectively communicated the areas that were most affected. 

It is imperative that moving forward the city learns from these hardships and creates a more resilient and equitable response framework. GIS can be used to:

1. Strengthen medical facilities by identifying areas in need of additional resources and ensuring hospitals are better equipped and prepared for future large-scale emergencies.

2. Improve communication during public health crises, providing residents with timely, accurate, and location-specific information about safety protocols and resource availability.

3. Map and prioritize the needs of the most vulnerable communities, ensuring that resources and support are directed where they are needed most during times of crisis.

4. Facilitate collaboration with community leaders and organizations, ensuring that response strategies reflect the unique needs of neighborhoods, with data-driven input at every level of the decision-making process.

As we continue to navigate the aftermath of the pandemic, we must decisive actions to ensure New York City is better equipped to handle future emergencies. Together, we can create a more resilient, inclusive, and prepared city for all of its residents.

Sincerely,

```{ojs}
{strName}
```
```{ojs}
viewof strName = Inputs.text({label: "Enter Name Here: "})
```
